services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: egt309_jupyter_notebook
    working_dir: /work
    ports:
      - "8888:8888"
    volumes:
      - ./notebook:/work/notebook
      - ./src:/work/src
      - ./data:/work/data
    environment:
      - JUPYTER_ENABLE_LAB=yes

  pipeline:
      build: .
      container_name: egt309_pipeline
      volumes:
        - ./src:/work/src
        - ./data:/work/data
      restart: "no"
      command: bash run.sh